apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kibana
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
      - name: kibana
        env:
        - name: KIBANA_ELASTICSEARCH_URL
          value: $(ELASTICSEARCH_LOGGING)
        - name: KIBANA_HOST
          value: 0.0.0.0
        - name: SERVER_BASEPATH
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        image: bitnami/kibana:6.8.12
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources:
          requests:
            cpu: 10m
